/**
 * Import profile for the certifiedcomic.shop export (16 rows, CSV columns: image, title,
 * product URL, vendor, price). The CSV carries no year, page quality, creators or
 * description, so every fact below was taken from the source product pages
 * (`/products/<handle>.json`, fetched 2026-09-15) and from the CGC labels legible in the
 * listing photos (certification number, cover date, creators, key comments, page quality).
 * Nothing was added from memory except Tales of Suspense #41's place in the Iron Man run,
 * which is documented everywhere.
 *
 * Pricing: the source price less 25 %, then rounded to the nearest price ending in .00, .49
 * or .99 (ties go to the .99). The source price is NOT shown as a compare-at price.
 */

export const source = "certifiedcomic-shop-2026-09";

export const pricing = { discount: 0.25, endings: [0, 49, 99] };

/** Placeholder seller for the source shop; contact name, handling time and policies are assumed and should be confirmed. */
export const sellers = [
  {
    key: "certified-comic-shop",
    slug: "certified-comic-shop",
    displayName: "Certified Comic Shop",
    email: "certifiedcomicshop@sellers.rarecomicscollectors.com",
    name: "Certified Comic Shop",
    businessType: "individual",
    countryCode: "US",
    shipsFromCountry: "US",
    handlingDays: 2,
    bio: "CGC-graded modern keys, retailer-incentive variants and Signature Series slabs, each photographed front and back in the holder before listing.",
    shippingPolicy: "Ships via USPS Priority Mail in new packing materials with tracking; slabs travel in a rigid mailer.",
    returnPolicy: "Return any slab in its original holder within the marketplace inspection window for a full refund.",
    customsNote: "International orders are declared at the sale price; import duties and taxes are the buyer's responsibility.",
  },
];

const M = "Marvel Comics";
const PHOTOS = "Photographed front and back in the holder; the certification number is legible on the label.";

/** Keyed by the source product handle. Fields mirror prisma/data/catalog-imports listings. */
export const listings = {
  "canto-1-cgc-9-6-third-printing-variant-2019": {
    slug: "canto-1-cgc-9-6-third-printing",
    title: "Canto", issue: "#1", publisher: "IDW Publishing", year: 2019, era: "Modern Age",
    grader: "CGC", grade: "9.6", label: "Universal Blue", certNumber: "4008073001",
    keyIssue: "First appearance of Canto — third printing with the Nicole Goux cover",
    creators: { writer: "David M. Booher", artist: "Drew Zucker", cover: "Nicole Goux" },
    summary: "Canto #1 (IDW Publishing, August 2019), third printing with the Nicole Goux cover — the first appearance of Canto. CGC 9.6, white pages.",
    description: `The first issue of IDW's Canto by David M. Booher and Drew Zucker, in its third printing with the Nicole Goux cover. The tin knight's quest began here, and this is the printing collectors of the series look for once the first two printings are gone.\n\nGraded CGC 9.6 Near Mint+ with white pages; the label reads "Third Printing". ${PHOTOS}`,
    highlights: ["First appearance of Canto", "Third printing, Nicole Goux cover", "CGC 9.6, white pages", "IDW Publishing, 2019 — Modern Age"],
    palette: ["#6d28d9", "#f59e0b"],
    attributes: { Character: "Canto", Printing: "Third printing", "Page quality": "White pages" },
    tags: ["Canto", "Modern Age", "CGC", "IDW"],
  },
  "war-of-the-realms-new-agents-of-atlas-1-cgc-9-6-2019": {
    slug: "war-of-the-realms-new-agents-of-atlas-1-cgc-9-6",
    title: "War of the Realms: New Agents of Atlas", issue: "#1", publisher: M, year: 2019, era: "Modern Age",
    grader: "CGC", grade: "9.6", label: "Universal Blue", certNumber: "4008073003",
    keyIssue: "First appearances of Luna Snow, Wave (Pearl Pangan), Crescent and Io; first U.S. appearance of Aero",
    creators: { writer: "Greg Pak", artist: "Gang Hyuk Lim", cover: "Billy Tan" },
    summary: "War of the Realms: New Agents of Atlas #1 (Marvel Comics, July 2019) — first appearances of Luna Snow, Wave, Crescent and Io, and the first U.S. appearance of Aero. CGC 9.6, white pages.",
    description: `The War of the Realms tie-in by Greg Pak and Gang Hyuk Lim that assembled a new Agents of Atlas. The CGC label records the first appearances of Luna Snow (Seol Hee), Wave (Pearl Pangan), Crescent (Dan Bi) and Io, and the first U.S. appearance of Aero (Lei Ling).\n\nGraded CGC 9.6 Near Mint+ with white pages; Billy Tan cover. ${PHOTOS}`,
    highlights: ["First appearances of Luna Snow, Wave, Crescent and Io", "First U.S. appearance of Aero", "CGC 9.6, white pages", "Marvel Comics, 2019 — Modern Age"],
    palette: ["#0e7490", "#fde047"],
    attributes: { Character: "Wave, Luna Snow, Aero, Crescent", "Page quality": "White pages" },
    tags: ["Agents of Atlas", "Modern Age", "CGC", "first appearance"],
  },
  "strange-academy-2-cgc-ss-9-8-adams-variant-2020": {
    slug: "strange-academy-2-cgc-ss-9-8-arthur-adams-variant",
    title: "Strange Academy", issue: "#2", publisher: M, year: 2020, era: "Modern Age",
    grader: "CGC", grade: "9.8", label: "Signature Series (Yellow)", certNumber: "3715979005",
    keyIssue: "Arthur Adams variant (Doyle Dormammu), signed by writer Skottie Young",
    creators: { writer: "Skottie Young", artist: "Humberto Ramos", cover: "Arthur Adams" },
    summary: "Strange Academy #2 (Marvel Comics, June 2020), Arthur Adams variant signed by Skottie Young on 23 September 2020. CGC Signature Series 9.8, white pages.",
    description: `The second issue of Skottie Young and Humberto Ramos's Strange Academy in the Arthur Adams variant, which puts Doyle Dormammu on the cover. Signed by Skottie Young in front of a CGC witness on 23 September 2020, so the signature is certified on the yellow Signature Series label.\n\nGraded CGC 9.8 Near Mint/Mint with white pages. ${PHOTOS}`,
    highlights: ["Arthur Adams variant — Doyle Dormammu", "Signed by Skottie Young, CGC Signature Series", "CGC 9.8, white pages", "Marvel Comics, 2020 — Modern Age"],
    palette: ["#7c3aed", "#f97316"],
    attributes: { Character: "Doyle Dormammu", Variant: "Arthur Adams variant", "Signed by": "Skottie Young (23 Sept 2020)", "Page quality": "White pages" },
    tags: ["Strange Academy", "Modern Age", "CGC", "Signature Series", "variant"],
  },
  "star-wars-7-cgc-9-8-moore-variant-2015": {
    slug: "star-wars-2015-7-cgc-9-8-moore-variant",
    title: "Star Wars (2015)", issue: "#7", publisher: M, year: 2015, era: "Modern Age",
    grader: "CGC", grade: "9.8", label: "Universal Blue", certNumber: "0267616010",
    keyIssue: "Tony Moore 1:25 incentive variant — first \"From the Journals of Old Ben Kenobi\" story",
    creators: { writer: "Jason Aaron", artist: "Simone Bianchi", cover: "Tony Moore" },
    summary: "Star Wars (2015) #7 (Marvel Comics, September 2015), Tony Moore 1:25 incentive variant — the first \"From the Journals of Old Ben Kenobi\" story. CGC 9.8, white pages.",
    description: `Issue #7 of Marvel's 2015 Star Wars series, by Jason Aaron and Simone Bianchi, carries the first "From the Journals of Old Ben Kenobi" story. This is the 1:25 retailer-incentive variant with Tony Moore's cover, noted on the label as "Moore Variant Cover".\n\nGraded CGC 9.8 Near Mint/Mint with white pages. ${PHOTOS}`,
    highlights: ["First \"From the Journals of Old Ben Kenobi\" story", "1:25 Tony Moore incentive variant", "CGC 9.8, white pages", "Marvel Comics, 2015 — Modern Age"],
    palette: ["#1e293b", "#facc15"],
    attributes: { Character: "Obi-Wan Kenobi", Variant: "1:25 Tony Moore incentive variant", "Page quality": "White pages" },
    tags: ["Star Wars", "Modern Age", "CGC", "variant"],
  },
  "wizard-ace-edition-witchblade-9-cgc-9-8": {
    slug: "witchblade-9-cgc-9-8-wizard-ace-edition",
    title: "Witchblade", issue: "#9", publisher: "Top Cow", year: 1996, era: "Modern Age",
    grader: "CGC", grade: "9.8", label: "Universal Blue", certNumber: "0027603010",
    keyIssue: "Wizard Ace Edition with acetate cover — Michael Turner cover and art",
    creators: { writer: "Various", artist: "Michael Turner", cover: "Michael Turner" },
    summary: "Witchblade #9 Wizard Ace Edition (Top Cow / Wizard, 1996), acetate cover, Michael Turner cover and art. CGC 9.8, white pages.",
    description: `The Wizard Ace Edition of Witchblade #9 — the acetate-cover reissue published by Top Cow with Wizard magazine in 1996, with Michael Turner's cover and interior art. The label reads "Acetate cover. Michael Turner cover and art."\n\nGraded CGC 9.8 Near Mint/Mint with white pages, in an early CGC holder with the red-bordered "Modern" label of that period. ${PHOTOS}`,
    highlights: ["Wizard Ace Edition, acetate cover", "Michael Turner cover and art", "CGC 9.8, white pages", "Top Cow / Wizard, 1996 — Modern Age"],
    palette: ["#111827", "#dc2626"],
    attributes: { Character: "Witchblade", Edition: "Wizard Ace Edition (acetate cover)", Holder: "Early CGC holder, red-bordered \"Modern\" label", "Page quality": "White pages" },
    tags: ["Witchblade", "Modern Age", "CGC", "Wizard Ace Edition"],
  },
  "blood-stained-teeth-1-cgc-9-8": {
    slug: "blood-stained-teeth-1-cgc-9-8",
    title: "Blood Stained Teeth", issue: "#1", publisher: "Image Comics", year: 2022, era: "Modern Age",
    grader: "CGC", grade: "9.8", label: "Universal Blue", certNumber: "4103217004",
    keyIssue: "First issue",
    creators: { writer: "Christian Ward", artist: "Patric Reynolds", cover: "Christian Ward" },
    summary: "Blood Stained Teeth #1 (Image Comics, April 2022), first printing, by Christian Ward and Patric Reynolds. CGC 9.8, white pages.",
    description: `The first issue of Image's vampire series Blood Stained Teeth, written by Christian Ward with art by Patric Reynolds and Ward's own cover. First printing.\n\nGraded CGC 9.8 Near Mint/Mint with white pages. ${PHOTOS}`,
    highlights: ["First issue, first printing", "Christian Ward story and cover, Patric Reynolds art", "CGC 9.8, white pages", "Image Comics, 2022 — Modern Age"],
    palette: ["#7f1d1d", "#f5f5f4"],
    attributes: { Printing: "First printing", "Page quality": "White pages" },
    tags: ["Blood Stained Teeth", "Modern Age", "CGC", "horror"],
  },
  "house-of-slaughter-1-cgc-9-8-2021": {
    slug: "house-of-slaughter-1-cgc-9-8-second-printing-foil",
    title: "House of Slaughter", issue: "#1", publisher: "Boom! Studios", year: 2021, era: "Modern Age",
    grader: "CGC", grade: "9.8", label: "Universal Blue", certNumber: "4056100003",
    keyIssue: "First appearance of Jace Boucher — second printing, silver foil logo, Miguel Mercado cover",
    creators: { writer: "James Tynion IV & Tate Brombal", artist: "Chris Shehan & Werther Dell'Edera", cover: "Miguel Mercado" },
    summary: "House of Slaughter #1 (Boom! Studios, November 2021), second printing with the silver-foil logo and Miguel Mercado cover — first appearance of Jace Boucher. CGC 9.8, white pages.",
    description: `The debut issue of House of Slaughter, the Something Is Killing the Children spin-off by James Tynion IV and Tate Brombal with art by Chris Shehan and Werther Dell'Edera, and the first appearance of Jace Boucher. This is the second printing with the silver-foil logo and Miguel Mercado's cover; the label reads "Second Printing/Foil Edition".\n\nGraded CGC 9.8 Near Mint/Mint with white pages. ${PHOTOS}`,
    highlights: ["First appearance of Jace Boucher", "Second printing, silver-foil logo, Miguel Mercado cover", "CGC 9.8, white pages", "Boom! Studios, 2021 — Modern Age"],
    palette: ["#0c0a09", "#14b8a6"],
    attributes: { Character: "Jace Boucher", Printing: "Second printing (silver foil logo)", "Page quality": "White pages" },
    tags: ["House of Slaughter", "Something Is Killing the Children", "Modern Age", "CGC"],
  },
  "dark-nights-metal-1-cgc-9-8-kubert-variant": {
    slug: "dark-nights-metal-1-cgc-9-8-kubert-variant",
    title: "Dark Nights: Metal", issue: "#1", publisher: "DC Comics", year: 2017, era: "Modern Age",
    grader: "CGC", grade: "9.8", label: "Universal Blue", certNumber: "3728648009",
    keyIssue: "Andy Kubert variant — first issue of Snyder and Capullo's Dark Nights: Metal event",
    creators: { writer: "Scott Snyder", artist: "Greg Capullo & Jonathan Glapion", cover: "Andy Kubert" },
    summary: "Dark Nights: Metal #1 (DC Comics, October 2017), Andy Kubert variant — the start of Scott Snyder and Greg Capullo's event. CGC 9.8, white pages.",
    description: `The first issue of Dark Nights: Metal, the Scott Snyder and Greg Capullo event that brought Batman, the Justice League and the Dark Multiverse together, in the Andy Kubert variant cover.\n\nGraded CGC 9.8 Near Mint/Mint with white pages. ${PHOTOS}`,
    highlights: ["Start of the Dark Nights: Metal event", "Andy Kubert variant cover", "CGC 9.8, white pages", "DC Comics, 2017 — Modern Age"],
    palette: ["#1f2937", "#ef4444"],
    attributes: { Character: "Batman", Variant: "Andy Kubert variant", "Page quality": "White pages" },
    tags: ["Batman", "Dark Nights: Metal", "Modern Age", "CGC", "variant"],
  },
  "maestro-world-war-m-4-cgc-9-8-design-variant": {
    slug: "maestro-world-war-m-4-cgc-9-8-design-variant",
    title: "Maestro: World War M", issue: "#4", publisher: M, year: 2022, era: "Modern Age",
    grader: "CGC", grade: "9.8", label: "Universal Blue", certNumber: "4167625024",
    keyIssue: "1:10 Germán Peralta design variant (Namor)",
    creators: { writer: "Peter David", artist: "Germán Peralta", cover: "Germán Peralta" },
    summary: "Maestro: World War M #4 (Marvel Comics, July 2022), 1:10 Germán Peralta design variant. CGC 9.8, white pages.",
    description: `Issue #4 of Peter David's Maestro: World War M in the 1:10 retailer-incentive design variant — Germán Peralta's character-design sheet for Namor, noted on the label as the "Design" variant cover.\n\nGraded CGC 9.8 Near Mint/Mint with white pages. ${PHOTOS}`,
    highlights: ["1:10 Germán Peralta design variant", "Peter David story", "CGC 9.8, white pages", "Marvel Comics, 2022 — Modern Age"],
    palette: ["#14532d", "#a3e635"],
    attributes: { Character: "Hulk, Namor", Variant: "1:10 Germán Peralta design variant", "Page quality": "White pages" },
    tags: ["Hulk", "Maestro", "Modern Age", "CGC", "variant"],
  },
  "ultimate-x-men-9-cgc-9-8-2001": {
    slug: "ultimate-x-men-9-cgc-9-8",
    title: "Ultimate X-Men", issue: "#9", publisher: M, year: 2001, era: "Modern Age",
    grader: "CGC", grade: "9.8", label: "Universal Blue", certNumber: "0108846027",
    keyIssue: null,
    creators: { writer: "Mark Millar", artist: "Tom Raney", cover: "Tom Raney" },
    summary: "Ultimate X-Men #9 (Marvel Comics, October 2001) from the Mark Millar run — part of \"Return to Weapon X\", with a Nick Fury appearance. CGC 9.8, white pages.",
    description: `An early issue of Ultimate X-Men from Mark Millar's original run, part of the "Return to Weapon X" storyline, with Tom Raney cover and art; the label notes the Nick Fury appearance.\n\nGraded CGC 9.8 Near Mint/Mint with white pages, in an early CGC holder. ${PHOTOS}`,
    highlights: ["\"Return to Weapon X\" storyline, Mark Millar run", "Nick Fury appearance; Tom Raney cover and art", "CGC 9.8, white pages", "Marvel Comics, 2001 — Modern Age"],
    palette: ["#1e3a8a", "#fbbf24"],
    attributes: { Character: "X-Men, Nick Fury", Holder: "Early CGC holder", "Page quality": "White pages" },
    tags: ["X-Men", "Ultimate Universe", "Modern Age", "CGC"],
  },
  "ultimate-x-men-7-cgc-9-8-2001": {
    slug: "ultimate-x-men-7-cgc-9-8",
    title: "Ultimate X-Men", issue: "#7", publisher: M, year: 2001, era: "Modern Age",
    grader: "CGC", grade: "9.8", label: "Universal Blue", certNumber: "0078117032",
    keyIssue: "First Ultimate Universe appearances of Nightcrawler and Rogue; first appearance of Dr. Abraham Cornelius — \"Return to Weapon X\" begins",
    creators: { writer: "Mark Millar", artist: "Adam Kubert & Art Thibert", cover: "Adam Kubert" },
    summary: "Ultimate X-Men #7 (Marvel Comics, August 2001) — first Ultimate Universe Nightcrawler and Rogue, first Dr. Abraham Cornelius. CGC 9.8, white pages.",
    description: `The issue that opens "Return to Weapon X" in Mark Millar and Adam Kubert's Ultimate X-Men, with the first Ultimate Universe appearances of Nightcrawler and Rogue and the first appearance of Dr. Abraham Cornelius; the label notes the Nightcrawler appearance.\n\nGraded CGC 9.8 Near Mint/Mint with white pages. ${PHOTOS}`,
    highlights: ["First Ultimate Universe appearances of Nightcrawler and Rogue", "First appearance of Dr. Abraham Cornelius", "CGC 9.8, white pages", "Marvel Comics, 2001 — Modern Age"],
    palette: ["#1e3a8a", "#fbbf24"],
    attributes: { Character: "X-Men, Nightcrawler, Rogue", "Page quality": "White pages" },
    tags: ["X-Men", "Ultimate Universe", "Modern Age", "CGC", "first appearance"],
  },
  "venom-1-cgc-ss-9-2-nm-remastered-sketch-variant-signed-by-cates-stegman-2018": {
    slug: "venom-2018-1-cgc-ss-9-2-remastered-sketch-variant",
    title: "Venom (2018)", issue: "#1", publisher: M, year: 2018, era: "Modern Age",
    grader: "CGC", grade: "9.2", label: "Signature Series (Yellow)", certNumber: "2494757018",
    keyIssue: "1:1000 Todd McFarlane remastered sketch variant, signed by Donny Cates and Ryan Stegman — first appearance of the Grendel symbiote dragon",
    creators: { writer: "Donny Cates", artist: "Ryan Stegman & JP Mayer", cover: "Todd McFarlane" },
    summary: "Venom (2018) #1 (Marvel Comics, July 2018), 1:1000 Todd McFarlane remastered sketch variant signed by Donny Cates and Ryan Stegman on 4 May 2019 — first appearance of the Grendel symbiote dragon. CGC Signature Series 9.2, white pages.",
    description: `The first issue of Donny Cates and Ryan Stegman's Venom (legacy #166), which introduced the Grendel symbiote dragon, in the 1:1000 retailer-incentive Remastered Sketch Edition of Todd McFarlane's cover. Signed by both Cates and Stegman in front of a CGC witness on 4 May 2019; both signatures are recorded on the yellow Signature Series label.\n\nGraded CGC 9.2 Near Mint− with white pages. Photographed in the holder from the front and back with label close-ups; the certification number is legible on the label.`,
    highlights: ["First appearance of the Grendel symbiote dragon", "1:1000 Todd McFarlane remastered sketch variant", "Signed by Donny Cates and Ryan Stegman, CGC Signature Series", "CGC 9.2, white pages — Marvel Comics, 2018"],
    palette: ["#0a0a0a", "#e5e5e5"],
    attributes: { Character: "Venom", Variant: "1:1000 Todd McFarlane remastered sketch variant", "Signed by": "Donny Cates, Ryan Stegman (4 May 2019)", "Page quality": "White pages" },
    tags: ["Venom", "Modern Age", "CGC", "Signature Series", "variant"],
  },
  "tales-of-suspense-41-cgc-8-5-vf-marvel-comics-1963": {
    slug: "tales-of-suspense-41-cgc-8-5",
    title: "Tales of Suspense", issue: "#41", publisher: M, year: 1963, era: "Silver Age",
    grader: "CGC", grade: "8.5", label: "Universal Blue", certNumber: "3950413002",
    keyIssue: "Third appearance of Iron Man — \"The Stronghold of Dr. Strange!\"",
    creators: { writer: "Various", artist: "Various", cover: "Various" },
    summary: "Tales of Suspense #41 (Marvel Comics, May 1963) — the third appearance of Iron Man. CGC 8.5, off-white to white pages.",
    description: `Tales of Suspense #41 is the third appearance of Iron Man, two issues after his debut in #39, with the golden armour on the cover of "The Stronghold of Dr. Strange!" (the scientist villain of this story, not the Sorcerer Supreme). Early Iron Man issues in Very Fine or better are increasingly hard to find.\n\nGraded CGC 8.5 Very Fine+ with off-white to white pages. Photographed front and back in the holder with a label close-up; the certification number is legible on the label.`,
    highlights: ["Third appearance of Iron Man", "CGC 8.5, off-white to white pages", "Marvel Comics, May 1963 — Silver Age"],
    palette: ["#78350f", "#fbbf24"],
    attributes: { Character: "Iron Man", "Page quality": "Off-white to white pages" },
    tags: ["Iron Man", "Silver Age", "CGC"],
  },
  "thor-18-cgc-9-6-stegman-variant": {
    slug: "thor-2020-18-cgc-9-6-stegman-variant",
    title: "Thor (2020)", issue: "#18", publisher: M, year: 2021, era: "Modern Age",
    grader: "CGC", grade: "9.6", label: "Universal Blue", certNumber: "3991244013",
    keyIssue: "Ryan Stegman variant, ComicTom101 & Mill Geek Comics exclusive — prelude to \"God of Hammers\"",
    creators: { writer: "Donny Cates", artist: "Pasqual Ferry & Bob Quinn", cover: "Ryan Stegman" },
    summary: "Thor (2020) #18 (Marvel Comics, December 2021), Ryan Stegman variant — a ComicTom101 & Mill Geek Comics exclusive and the \"God of Hammers\" prelude. CGC 9.6, white pages.",
    description: `Issue #18 (legacy #744) of the 2020 Thor series by Donny Cates with art by Pasqual Ferry and Bob Quinn — the prelude to "God of Hammers", in which the All-Father returns to Midgard and enlists Loki. This is the Ryan Stegman variant cover, recorded on the label as a ComicTom101 & Mill Geek Comics exclusive.\n\nGraded CGC 9.6 Near Mint+ with white pages. ${PHOTOS}`,
    highlights: ["\"God of Hammers\" prelude — Loki returns", "Ryan Stegman variant, ComicTom101 & Mill Geek Comics exclusive", "CGC 9.6, white pages", "Marvel Comics, 2021 — Modern Age"],
    palette: ["#1e40af", "#f59e0b"],
    attributes: { Character: "Thor, Loki", Variant: "Ryan Stegman variant (ComicTom101 & Mill Geek Comics exclusive)", "Page quality": "White pages" },
    tags: ["Thor", "Modern Age", "CGC", "variant"],
  },
  "nebula-1-cgc-9-8-remastered-variant": {
    slug: "nebula-1-cgc-9-8-ron-lim-remastered-variant",
    title: "Nebula", issue: "#1", publisher: M, year: 2020, era: "Modern Age",
    grader: "CGC", grade: "9.8", label: "Universal Blue", certNumber: "3981914009",
    keyIssue: "First solo series for Nebula — 1:100 Ron Lim remastered variant",
    creators: { writer: "Vita Ayala", artist: "Claire Roe", cover: "Ron Lim" },
    summary: "Nebula #1 (Marvel Comics, April 2020), 1:100 Ron Lim remastered variant — the first solo series for Nebula. CGC 9.8, white pages.",
    description: `The first issue of Nebula's first solo series, by Vita Ayala and Claire Roe, in the 1:100 retailer-incentive Ron Lim remastered variant; the label reads "Remastered Edition".\n\nGraded CGC 9.8 Near Mint/Mint with white pages. ${PHOTOS}`,
    highlights: ["First solo series for Nebula", "1:100 Ron Lim remastered variant", "CGC 9.8, white pages", "Marvel Comics, 2020 — Modern Age"],
    palette: ["#312e81", "#22d3ee"],
    attributes: { Character: "Nebula", Variant: "1:100 Ron Lim remastered variant", "Page quality": "White pages" },
    tags: ["Nebula", "Guardians of the Galaxy", "Modern Age", "CGC", "variant"],
  },
  "batman-227-cgc-8-0-v-f": {
    slug: "batman-227-cgc-8-0",
    title: "Batman", issue: "#227", publisher: "DC Comics", year: 1970, era: "Bronze Age",
    grader: "CGC", grade: "8.0", label: "Universal Blue", certNumber: "0271066017",
    keyIssue: "Classic Neal Adams cover, an homage to Detective Comics #31",
    creators: { writer: "Denny O'Neil & Mike Friedrich", artist: "Irv Novick, Dick Giordano & Mike Esposito", cover: "Neal Adams" },
    summary: "Batman #227 (DC Comics, December 1970) — the classic Neal Adams cover homage to Detective Comics #31. CGC 8.0, cream to off-white pages.",
    description: `Batman #227 carries one of Neal Adams's most reproduced covers, a homage to Detective Comics #31 from 1939, over "The Demon of Gothos Mansion!" by Denny O'Neil and Irv Novick — a gothic Bronze Age mystery that sends Batman into a sinister mansion after a missing young woman — plus a Robin backup story. The CGC label reads "Classic cover. Detective Comics #31 cover homage."\n\nGraded CGC 8.0 Very Fine with cream to off-white pages. ${PHOTOS}`,
    highlights: ["Classic Neal Adams cover — homage to Detective Comics #31", "\"The Demon of Gothos Mansion!\" by O'Neil and Novick; Robin backup", "CGC 8.0, cream to off-white pages", "DC Comics, 1970 — Bronze Age"],
    palette: ["#1f2937", "#eab308"],
    attributes: { Character: "Batman, Robin", "Page quality": "Cream to off-white pages" },
    tags: ["Batman", "Bronze Age", "CGC", "Neal Adams"],
  },
};
